version: '3.3'
services: 
 mysql:
  container_name: mysql5
  image: mysql:5.6.47
  environment: 
   MYSQL_ROOT_PASSWORD: "123",
   MYSQL_DATABASE: "samel",
   TZ: America/Manaus
  ports:
   - '3307:3306'
  volumes:
   - mysql-db:/var/lib/mysql
volumes: 
 mysql-db:
networks:
 default:
  external:
   name: mysql-network